name: build-master

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          cd ./list
          echo "begin installing"
          npm install
          npm set CI=false
          echo "begin generating main-page"
          npm run build-linux
          cp -r ./build ../build-part
          cd ..
          cd ./docs-src
          # npm install node-sass@latest
          npm update
          npm install
          npm i -g gatsby-cli
          gatsby build --prefix-paths
          cp -r ./public ../docs-part
          cd ..
          cp -r ./docs-part ./build-part/docs
          # mkdir ./public
          # cp -r ./public ../page/docs
          # echo test, and deploy your project.
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./build-part/
          if-no-files-found: error
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: ./build-part # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
  sync-gitee:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: sync
        uses: Yikun/hub-mirror-action@master
        with:
          # 必选，需要同步的Github用户（源）
          src: github/SDU-Mirrors
          # 必选，需要同步到的Gitee的用户（目的）
          dst: gitee/mirrors-sdu
          # 必选，Gitee公钥对应的私钥，https://gitee.com/profile/sshkeys
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          # 必选，Gitee对应的用于创建仓库的token，https://gitee.com/profile/personal_access_tokens
          dst_token: ${{ secrets.GITEE_TOKEN }}
          # 只同步指定仓库
          static_list: front-end