name: sync
on:
  workflow_dispatch:
  push:

jobs:
  sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: sync
        uses: Yikun/hub-mirror-action@master
        with:
          # 必选，需要同步的Github用户（源）
          src: github/SDU-Mirrors
          # 必选，需要同步到的Gitee的用户（目的）
          dst: gitee/mirrors-sdu
          # 必选，Gitee公钥对应的私钥，https://gitee.com/profile/sshkeys
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          # 必选，Gitee对应的用于创建仓库的token，https://gitee.com/profile/personal_access_tokens
          dst_token: ${{ secrets.GITEE_TOKEN }}
          # 只同步指定仓库
          static_list: front-end